name: Teho Promoter Application Android (Release)

on:
  push:
    branches: [ main ]

jobs: 
  build:
    name: Build APK
    needs: []
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with: 
        name: 'apk'
        path: build/app/outputs/apk/release/app-release.apk

  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: 'apk'

      - name: Upload APK to S3
        id: upload
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: ${{steps.download.outputs.download-path}}/app-release.apk
          destination-dir: apk
          output-file-url: true

      - name: Show URL
        run: echo '${{ steps.upload.outputs.file-url }}'

      - name: APK link to server
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.SERVER_UPLOAD_LINK }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"file_url": ${{ steps.upload.outputs.file-url, "version": ${{ secrets.PROMOTER_APP_VERSION }}, "build": PROMOTER_APP_BUILD_NUMBER }}}'
